/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    services: Service;
    testimonials: Testimonial;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'hero-section': HeroSection;
    'projects-section': ProjectsSection;
    'contact-section': ContactSection;
    'about-section': AboutSection;
    'process-section': ProcessSection;
    'footer-section': FooterSection;
    'company-info': CompanyInfo;
  };
  globalsSelect: {
    'hero-section': HeroSectionSelect<false> | HeroSectionSelect<true>;
    'projects-section': ProjectsSectionSelect<false> | ProjectsSectionSelect<true>;
    'contact-section': ContactSectionSelect<false> | ContactSectionSelect<true>;
    'about-section': AboutSectionSelect<false> | AboutSectionSelect<true>;
    'process-section': ProcessSectionSelect<false> | ProcessSectionSelect<true>;
    'footer-section': FooterSectionSelect<false> | FooterSectionSelect<true>;
    'company-info': CompanyInfoSelect<false> | CompanyInfoSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  slug: string;
  /**
   * Featured projects appear prominently on the homepage
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first
   */
  order?: number | null;
  /**
   * Short description for project cards
   */
  description: string;
  /**
   * Detailed project description for project detail page
   */
  fullDescription: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Client name (optional)
   */
  client?: string | null;
  /**
   * Project duration (e.g., "6 months")
   */
  duration?: string | null;
  /**
   * Year completed
   */
  year?: string | null;
  heroImage: number | Media;
  /**
   * Optional .fbx 3D model. If provided, the project card shows an interactive 3D viewer instead of the hero image. FBX files include geometry, materials, and textures in one file.
   */
  model3d?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  technologies?:
    | {
        technology: string;
        id?: string | null;
      }[]
    | null;
  /**
   * What was the main challenge of this project?
   */
  challenge?: string | null;
  /**
   * How did we solve the challenge?
   */
  solution?: string | null;
  results?:
    | {
        metric: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional link for live project or case study
   */
  ctaLink?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  description: string;
  /**
   * Icon type for the service
   */
  icon:
    | 'lightning-bolt'
    | 'chip'
    | 'ruler'
    | 'triangle-ruler'
    | 'pcb'
    | 'code-brackets'
    | 'cube'
    | 'printer'
    | 'cog'
    | 'beaker'
    | 'lightbulb';
  /**
   * Lower numbers appear first
   */
  order?: number | null;
  link?: {
    text?: string | null;
    href?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * The testimonial text from the client
   */
  quote: string;
  author: string;
  role: string;
  company: string;
  /**
   * Optional avatar image for the author
   */
  avatar?: (number | null) | Media;
  /**
   * Featured testimonials appear on the homepage
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first
   */
  order?: number | null;
  /**
   * Rating out of 5 stars
   */
  rating?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  featured?: T;
  order?: T;
  description?: T;
  fullDescription?: T;
  client?: T;
  duration?: T;
  year?: T;
  heroImage?: T;
  model3d?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  technologies?:
    | T
    | {
        technology?: T;
        id?: T;
      };
  challenge?: T;
  solution?: T;
  results?:
    | T
    | {
        metric?: T;
        value?: T;
        id?: T;
      };
  ctaLink?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  icon?: T;
  order?: T;
  link?:
    | T
    | {
        text?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  author?: T;
  role?: T;
  company?: T;
  avatar?: T;
  featured?: T;
  order?: T;
  rating?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Manage the main hero section on the homepage
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-section".
 */
export interface HeroSection {
  id: number;
  /**
   * Small text above the main title
   */
  subtitle?: string | null;
  /**
   * Main headline displayed in the hero section
   */
  title: string;
  /**
   * Hero description text
   */
  description?: string | null;
  primaryCTA?: {
    text?: string | null;
    href?: string | null;
  };
  secondaryCTA?: {
    text?: string | null;
    href?: string | null;
  };
  /**
   * Background image for the hero section
   */
  backgroundImage?: (number | null) | Media;
  /**
   * Upload a background video (mp4 or webm). Overrides background image if provided.
   */
  backgroundVideo?: (number | null) | Media;
  /**
   * Add dark overlay over background
   */
  overlay?: boolean | null;
  /**
   * Overlay opacity percentage (0-100)
   */
  overlayOpacity?: number | null;
  /**
   * Show the animated scroll arrow at the bottom of the hero
   */
  scrollIndicator?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage the Projects section content on the homepage
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects-section".
 */
export interface ProjectsSection {
  id: number;
  /**
   * Main heading for the projects section on the homepage
   */
  title: string;
  /**
   * Header content for the /projects page
   */
  pageHeader?: {
    /**
     * Small text displayed above the main title
     */
    label?: string | null;
    /**
     * Main heading for the projects page
     */
    title?: string | null;
    /**
     * Introductory text displayed below the title
     */
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage the Contact section form labels and content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-section".
 */
export interface ContactSection {
  id: number;
  /**
   * Section heading
   */
  title: string;
  /**
   * Label for name field
   */
  nameLabel: string;
  /**
   * Placeholder for name field
   */
  namePlaceholder: string;
  /**
   * Label for email field
   */
  emailLabel: string;
  /**
   * Placeholder for email field
   */
  emailPlaceholder: string;
  /**
   * Label for message field
   */
  messageLabel: string;
  /**
   * Placeholder for message field
   */
  messagePlaceholder: string;
  /**
   * Text for submit button
   */
  submitButtonText: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage the about section on the homepage
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-section".
 */
export interface AboutSection {
  id: number;
  /**
   * Small text above the main title
   */
  subtitle: string;
  /**
   * Main heading for the about section
   */
  title: string;
  /**
   * Main description text
   */
  description: string;
  /**
   * Image displayed in the about section
   */
  image?: (number | null) | Media;
  /**
   * Position of the image relative to the text
   */
  imagePosition?: ('left' | 'right') | null;
  /**
   * Key statistics to display
   */
  stats?:
    | {
        /**
         * Stat value (e.g., "150+", "40+")
         */
        value: string;
        /**
         * Stat label (e.g., "Prototypes Delivered")
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional call-to-action button
   */
  cta?: {
    text?: string | null;
    /**
     * URL or anchor (e.g., "#process", "/contact")
     */
    href?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage the process/workflow section on the homepage
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "process-section".
 */
export interface ProcessSection {
  id: number;
  /**
   * Small text above the main title
   */
  subtitle: string;
  /**
   * Main heading for the process section
   */
  title: string;
  /**
   * List of steps in your process
   */
  steps: {
    /**
     * Step number to display (e.g., "01", "02")
     */
    number: string;
    /**
     * Icon to display for this step
     */
    icon: 'lightbulb' | 'design' | 'flask' | 'shield' | 'cog' | 'rocket';
    /**
     * Title of the process step
     */
    title: string;
    /**
     * Description of what happens in this step
     */
    description: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage footer content, links, and services
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-section".
 */
export interface FooterSection {
  id: number;
  /**
   * List of services to display in the footer
   */
  services?:
    | {
        label: string;
        /**
         * URL or anchor (e.g., "/#solutions", "/services")
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Toggle the quick links section in footer
   */
  showQuickLinks?: boolean | null;
  /**
   * Legal links displayed at the bottom of the footer
   */
  legalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Copyright text (year will be automatically added)
   */
  copyrightText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage company contact information and social media links (used in footer, contact section, etc.)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-info".
 */
export interface CompanyInfo {
  id: number;
  /**
   * Official company name
   */
  companyName: string;
  /**
   * Short company description/tagline
   */
  tagline?: string | null;
  /**
   * Company logo (used in footer, navbar, etc.)
   */
  logo?: (number | null) | Media;
  /**
   * Primary contact email
   */
  email: string;
  /**
   * Primary contact phone number
   */
  phone: string;
  /**
   * Phone number for tel: links (digits only, e.g., "+1234567890")
   */
  phoneHref?: string | null;
  /**
   * Physical address (optional)
   */
  address?: {
    street?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
    country?: string | null;
  };
  /**
   * Social media profile links
   */
  socialMedia?: {
    /**
     * Full URL to GitHub profile/organization
     */
    github?: string | null;
    /**
     * Full URL to LinkedIn profile/company page
     */
    linkedin?: string | null;
    /**
     * Full URL to Twitter/X profile
     */
    twitter?: string | null;
    /**
     * Full URL to Facebook page
     */
    facebook?: string | null;
    /**
     * Full URL to Instagram profile
     */
    instagram?: string | null;
  };
  /**
   * Business operating hours (optional)
   */
  businessHours?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-section_select".
 */
export interface HeroSectionSelect<T extends boolean = true> {
  subtitle?: T;
  title?: T;
  description?: T;
  primaryCTA?:
    | T
    | {
        text?: T;
        href?: T;
      };
  secondaryCTA?:
    | T
    | {
        text?: T;
        href?: T;
      };
  backgroundImage?: T;
  backgroundVideo?: T;
  overlay?: T;
  overlayOpacity?: T;
  scrollIndicator?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects-section_select".
 */
export interface ProjectsSectionSelect<T extends boolean = true> {
  title?: T;
  pageHeader?:
    | T
    | {
        label?: T;
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-section_select".
 */
export interface ContactSectionSelect<T extends boolean = true> {
  title?: T;
  nameLabel?: T;
  namePlaceholder?: T;
  emailLabel?: T;
  emailPlaceholder?: T;
  messageLabel?: T;
  messagePlaceholder?: T;
  submitButtonText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-section_select".
 */
export interface AboutSectionSelect<T extends boolean = true> {
  subtitle?: T;
  title?: T;
  description?: T;
  image?: T;
  imagePosition?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        text?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "process-section_select".
 */
export interface ProcessSectionSelect<T extends boolean = true> {
  subtitle?: T;
  title?: T;
  steps?:
    | T
    | {
        number?: T;
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-section_select".
 */
export interface FooterSectionSelect<T extends boolean = true> {
  services?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  showQuickLinks?: T;
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  copyrightText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-info_select".
 */
export interface CompanyInfoSelect<T extends boolean = true> {
  companyName?: T;
  tagline?: T;
  logo?: T;
  email?: T;
  phone?: T;
  phoneHref?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zip?: T;
        country?: T;
      };
  socialMedia?:
    | T
    | {
        github?: T;
        linkedin?: T;
        twitter?: T;
        facebook?: T;
        instagram?: T;
      };
  businessHours?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}